version: '3.9'   

services:
  postgres:
    image: moschopsd20/local-postgres-workspace
    container_name: local-postgres
    ports:
      - '5000:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
    postgres: